# Generated by Django 4.2.6 on 2023-11-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('inn', models.BigIntegerField(unique=True, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Upd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date', models.DateField(verbose_name='Дата')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер УПД')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'УПД',
                'verbose_name_plural': 'УПД',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.object', verbose_name='Объект')),
                ('upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.upd', verbose_name='УПД')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер платежа')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.counterparty', verbose_name='Контрагент')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ObjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Взнос')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа пользователя')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Взнос',
                'verbose_name_plural': 'Взносы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='object',
            name='group',
            field=models.ManyToManyField(through='reports.ObjectGroup', to='auth.group', verbose_name='Группа пользователя'),
        ),
    ]
