# Generated by Django 4.2.6 on 2023-10-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Группа пользователя')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='Counterparties',
            new_name='Counterparty',
        ),
        migrations.CreateModel(
            name='Upd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date', models.DateField(verbose_name='Дата')),
                ('number', models.IntegerField(verbose_name='Номер УПД')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'УПД',
                'verbose_name_plural': 'УПД',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('upd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.upd', verbose_name='УПД')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.FloatField(verbose_name='Стоимость')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.counterparty', verbose_name='Контрагент')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['id'],
            },
        ),
    ]
