# Generated by Django 4.2.6 on 2023-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectgroup',
            options={'ordering': ['id'], 'verbose_name': 'Выплата', 'verbose_name_plural': 'Выплаты'},
        ),
        migrations.AlterField(
            model_name='objectgroup',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выплата'),
        ),
    ]
