# Generated by Django 4.2.6 on 2023-11-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_objectgroup_options_alter_objectgroup_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectgroup',
            options={'ordering': ['id'], 'verbose_name': 'Объект группы', 'verbose_name_plural': 'Объекты групп'},
        ),
        migrations.AlterModelOptions(
            name='upd',
            options={'ordering': ['id'], 'verbose_name': 'Услуга УПД', 'verbose_name_plural': 'Услуги УПД'},
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
    ]
