# Generated by Django 4.2.6 on 2025-11-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_objectgroup_options_alter_upd_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='inn',
            field=models.CharField(max_length=30, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='upd',
            name='number',
            field=models.IntegerField(verbose_name='Номер УПД'),
        ),
        migrations.AddConstraint(
            model_name='upd',
            constraint=models.UniqueConstraint(fields=('number', 'date'), name='unique_number_per_date'),
        ),
    ]
