# Generated by Django 4.2.6 on 2023-10-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_payment_amount_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='inn',
            field=models.BigIntegerField(verbose_name='ИНН'),
        ),
    ]
