# Generated by Django 4.2.6 on 2023-10-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_counterparty_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='service',
            name='upd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.upd', verbose_name='УПД'),
        ),
        migrations.AlterField(
            model_name='upd',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.counterparty', verbose_name='Контрагент'),
        ),
    ]
