# Generated by Django 4.2.6 on 2023-10-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0006_alter_payment_counterparty_alter_payment_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа пользователя'),
        ),
    ]
