# Generated by Django 4.2.6 on 2023-10-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_object_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='inn',
            field=models.BigIntegerField(unique=True, verbose_name='ИНН'),
        ),
    ]
