# Generated by Django 4.2.6 on 2023-10-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0008_alter_counterparty_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='group',
        ),
        migrations.AlterField(
            model_name='upd',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер УПД'),
        ),
        migrations.CreateModel(
            name='ObjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Взнос')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа пользователя')),
                ('object_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Взнос',
                'verbose_name_plural': 'Вносы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='object',
            name='group',
            field=models.ManyToManyField(through='reports.ObjectGroup', to='auth.group', verbose_name='Группа пользователя'),
        ),
    ]
